spring.application.name=sistema-eventos
server.port=8080

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_eventos
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=miClaveSecretaSuperSeguraParaElSistemaDeEventos2026CambiarEnProduccion
jwt.expiration=86400000
